AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String
    Description: Nombre del entorno (dev/qa/prod)
    Default: dev
  pBranchName:
    Description: "Nombre de la rama (en minúsculas, sin símbolos ni espacios)"
    Type: String
  pArtifactsBucket:
    Description: "Bucket de artefactos (en minúsculas, sin símbolos ni espacios)"
    Type: String
  pAWSRegion:
    Description: "Región de AWS (en minúsculas, sin símbolos ni espacios)"
    Type: String
  pAWSAccountId:
    Description: "ID de la cuenta de AWS (en minúsculas, sin símbolos ni espacios)"
    Type: String
  pAWSAccountOptId:
    Description: "ID de la cuenta optimizadora de AWS (en minúsculas, sin símbolos ni espacios)"
    Type: String
  pAccountName:
    Description: "Nombre de la cuenta de AWS (en minúsculas, sin símbolos ni espacios)"
    Type: String
  pTeamName:
    Description: "Nombre del equipo de AWS (en minúsculas, sin símbolos ni espacios)"
    Type: String
  pdeploymentDate:
    Description: "Fecha de despliegue (en minúsculas, sin símbolos ni espacios)"
    Type: String

Resources:
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: s3-to-lambda
      EventPattern: >-
        {"source":["aws.s3"],"detail-type":["Object
        Created"],"detail":{"bucket":{"name":["stage-file-da-160885287080-160885287080"]},"object":{"key":[{"prefix":"input/regional/eta/simplyroute/"}]}}}
      State: ENABLED
      EventBusName: default
      Targets:
        - Id: Id31889617-1882-40bd-b54d-f2b74669ff6a
          Arn:
            Fn::Sub: >-
              arn:aws:lambda:us-east-1:160885287080:function:lambda-da-eta-sp
  
  
#   MyEventRule:
#       Type: AWS::Events::Rule
#       Properties:
#         ScheduleExpression: "cron(0 12 * * ? *)" # Cambia según la frecuencia que necesites
#         State: "ENABLED"
#         Targets:
#           - Id: "MyLambdaTarget"
#             Arn: "arn:aws:lambda:us-east-1:039612881651:function:function-dev-prueba"



#   S3CreateObjectRule:
#     Type: AWS::Events::Rule
#     Properties:
#       Name: S3CreateObjectEventRuleprueba
#       Description: "Regla que captura eventos de creación de objetos en S3 y activa una función Lambda."
#       EventPattern:
#         source:
#           - "aws.s3"
#         detail-type:
#           - "AWS API Call via CloudTrail"
#         detail:
#           eventSource:
#             - "s3.amazonaws.com"
#           eventName:
#             - "PutObject"
#             - "CompleteMultipartUpload"
#           requestParameters:
#             bucketName:
#               - "koa-prueba-345345345345"
#       State: ENABLED
#       Targets:
#         - Id: LambdaTarget
#           Arn: arn:aws:lambda:us-east-1:039612881651:function:lambda-example-Josemaria-api_Misupply



#   LambdaInvokePermission:
#     Type: AWS::Lambda::Permission
#     Properties:
#       FunctionName: arn:aws:lambda:us-east-1:039612881651:function:lambda-example-Josemaria-api_Misupply
#       Action: lambda:InvokeFunction
#       Principal: events.amazonaws.com
#       SourceArn: !GetAtt S3CreateObjectRule.Arn
# Outputs: 
#   MyEventRule:
#     Description: MyEventRule Arn
#     Value: !GetAtt MyEventRule.Arn
#     Export:
#       Name: DA-MyEventRule
