AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "Aws region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOptId:
    Description: "Aws account optimizador Id(all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String

Resources:
  
  LambdaMioptimizadorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${pTeamName}-${pAccountName}-${Stage}-stage-file"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
        - "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: !Sub "${pTeamName}-${pAWSAccountId}-access-to-s3-policy-stage-file"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessToS3Policy
                Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub "arn:aws:s3:::stage-file-{pTeamName}-{pAWSAccountId}-{pAWSAccountId}/*"
              - Sid: ReadSecretsManager
                Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:ListSecrets"
                Resource:
                  - !Sub "arn:aws:secretsmanager:${pAWSRegion}:${pAWSAccountId}:secret:*"
              - Sid: AccessTosqsPolicy
                Effect: Allow
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                Resource: 
                  - "*"
              - Sid: AccessTosqsPolicyghg
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  etaSplambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "lambda-{pTeamName}-eta-sp"
      Description: "Lambda function desplegada dinámicamente con 'Hola Mundo'"
      MemorySize: 256
      Timeout: 30
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print("Hola Mundo")
              return {
                  'statusCode': 200,
                  'body': 'Hola Mundo'
              }
      Role: !GetAtt LambdaMioptimizadorRole.Arn
      Handler: index.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          ENVIRONMENT: !Ref Stage
          REGION: !Ref pAWSRegion
          ACCOUNT_ID: !Ref pAWSAccountId
          BRANCH_NAME: !Ref pBranchName
      Layers:
        - !Ref dataWranglerLayer
        - !Ref requestLayer
  
  etaMplambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "lambda-{pTeamName}-eta-ml"
      Description: "Lambda function desplegada dinámicamente con 'Hola Mundo'"
      MemorySize: 256
      Timeout: 30
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print("Hola Mundo")
              return {
                  'statusCode': 200,
                  'body': 'Hola Mundo'
              }
      Role: !GetAtt LambdaMioptimizadorRole.Arn
      Handler: index.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          ENVIRONMENT: !Ref Stage
          REGION: !Ref pAWSRegion
          ACCOUNT_ID: !Ref pAWSAccountId
          BRANCH_NAME: !Ref pBranchName
      Layers:
        - !Ref dataWranglerLayer
        - !Ref requestLayer


  dataWranglerLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: dev-artifacts-dev-josemaria
        S3Key: layers/awswrangler-layer-py3-9.zip
      Description: Data Wrangler Layer for Python 3.9
      LayerName: !Sub awswrangler-layer-py3-9-${Stage}

  requestLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
        - python3.12
      Content:
        S3Bucket: dev-artifacts-dev-josemaria
        S3Key: layers/request-layer-py3-12.zip
      Description: Request Layer for Python 3.12
      LayerName: !Sub request-py3-12-${Stage}

Outputs: 
  etaSplambda:
    Description: etaSplambda Arn
    Value: !GetAtt etaSplambda.Arn
    Export:
      Name: DA-etaSplambdaArn

  etaMplambda:
    Description: etaMplambda Arn
    Value: !GetAtt etaMplambda.Arn
    Export:
      Name: DA-etaMplambdaArn
